# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
headTitle: 学习吧
title: ''
subtitle: 致最好的我们
description: 记录日常用到的边边角角，悟已往之不谏，知来者之可追
keywords: 博客
author: didton
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://github.com/XtRqHelper/portal
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
#  line_number: true
#  auto_detect: false
#  tab_replace:

prism_plugin:
  mode: 'preprocess'   # realtime/preprocess
  theme: 'tomorrow'
  line_number: true   # default false
  custom_css:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:


feed: # RSS订阅插件
  type: atom
  path: atom.xml
  limit: 20
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

plugins: hexo-generate-feed

search:
  path: search.json
  field: post

permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

# 是否在首页显示音乐
music:
  enable: false
  title:     	    #非吸底模式有效
    enable: true
    show: 听听音乐
  server: netease   #require music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 572819430     #require song id / playlist id / album id / search keyword
  fixed: true      # 开启吸底模式
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.3       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠

#ICP备案信息尾部显示
icp:
  enable: false
  url: # 备案链接
  text: # 备案信息
